### ISSUE TITLE
FEATURE REQUEST : Color Filtering and Toggleability

### ISSUE THREAD

**Issue by Temil2006** [MightyPirates/Scannable#16]
really like this mod, but would love to see the following 2 features added to this.

FEATURE REQUEST:
1. ability to "filter" colors. Meaning, if there are multiple Ores with the same / similar colors, having a filter ability to only display specific colors would be nice. On moded worlds with alot of resources, This mod scanning makes the entire area look like a candy swirl within the Rocks. Filtering would allow ability to target specific colors, but not exactly specific resources depending on the colors.

2. Ability to toggle the scanning on/off .. but with the continues resource cost (a high cost) if you continue to use it. having this as an option within the item  so that client users would be able to select either 1 time scan or toggle continues scanning.

**Comment by fnuecke** [comment]
Thanks for the feedback!

1. Use the block module and configure it to the specific ore you're looking for. I think that's good enough and the alternative is rather... configuration heavy (because it's pretty much impossible to automate getting a *visually logical* color from a block).

2. Eh, I think that'd be a bit too much, sorry. And you can use it in the off-hand after all, so it really shouldn't hinder you that much. Also there's the technical problem of continually scanning - right now, the scan is distributed over multiple frames during the charge-up, avoiding stutters.
