### ISSUE TITLE
Internet/Network module?

### ISSUE THREAD

**Issue by dunstad** [MightyPirates/Scannable#26]
I think it would be pretty neat if there was a module for the Scanner that would allow you to transmit data, similar to the internet and network cards for OpenComputers robots. Is this reasonably possible, or too big an addition for a small mod?

**Comment by fnuecke** [comment]
Mm, while it'd be kinda neat, two things that speak against that IMHO:
- lore: it's a scanner, not a transmitter ;)
- technical: the scanning is done on the client (with one exception, that being structures IIRC), so the results would have to be sent to the server... which would allow clients to spam potentially large data packets to server (tile)entities, which is something I'm always wary about.

That said, if some addon mod for OC wanted to do that, I could add something to the API so that `ScanResultProviders` could be notified with all results after a scan. Then that addon could to the synching-to-server itself. If that ever becomes relevant, feel free to reopen this :)
