### ISSUE TITLE
[Suggestion] Identifying non-vanilla dungeons

### ISSUE THREAD

**Issue by Boolyman** [MightyPirates/Scannable#32]
Can I recommend a module to identify structures and dungeons that aren't vanilla.  Most modpacks have other types of dungeons nowadays.   I know its harder than it sounds, but ways to code it might be:

-Code the mod to highlight the general area anytime there is a higher than normal concentration of mob spawners within a close proximity to each other (i.e. 20-25 block radius).  This usually indicates a dungeon of some sort.

-Code the mod to look for "rooms"... flat areas with a 90 degree angle on each corner.  This doesn't happen often, if ever, in normal world gen, unless its a structure of some sort.

**Comment by fnuecke** [comment]
Trying to detect patterns in the world is really really costly; add to that that structures are generally detected a good bit past the area of loaded chunks (because their coordinates are computed). The sane solution to this would be MC/Forge adding an option for mods to hook into the structure lookup logic vanilla MC provides.
