### ISSUE TITLE
Certain ores are not configurable

### ISSUE THREAD

**Issue by Pandemoneus** [MightyPirates/Scannable#35]
In 1.12, certain ores can not be configured. For example, the NuclearCraft ores thorium (oreThorium) and boron (oreBoron) always appear as common ores in the default color. Even when changing the color of these ores and marking them as rare ores, they still appear as common in the default color.

Astral Sorcery ores do not appear at all, although they have an ore dictionary entry.

From my research, the issue with the NuclearCraft ores seems to be that they all use the same id, but different metadata.

**Comment by fnuecke** [comment]
For state-specific ores, use `statesCommon` and `statesRare` config options. Format of entries is `blockid[property=value]`, for multiple properties comma-separate them e.g. `opencomputers:case[tier=1,running=true]` (not valid, just an example). Basically the same thing you see in the debug F3 view when looking at a block.

If that doesn't work the block might have a tile entity; those cannot be properly distinguished I'm afraid.

**Comment by guillaumearm** [comment]
I have set my `statesCommon` config option for projectred copper,  however it still appear as common ores (with the default lightblue color) using a rare module in my scanner.

I think you should re-open this issue because there is a problem for sure.

![image](https://user-images.githubusercontent.com/16897658/40866483-1ef48cb2-65fe-11e8-929f-13c9b0354565.png)

**EDIT:**

In addition : I cannot blacklist a block state
