### ISSUE TITLE
Fatal Error when loading singleplayer world

### ISSUE THREAD

**Issue by brisingraerowing** [MightyPirates/Scannable#38]
[Error Stacktrace](https://gist.github.com/BrisingrAerowing/a5afe77895fb5fbd676e404ebf401b24)

This happened when I went into a singleplayer world with Scannable v1.6.3.16. I ended up getting kicked back to the multiplayer selection screen.

**Comment by brisingraerowing** [comment]
It looks like some mod is returning `null` when getPickBlock is called. I'll try to figure out which one that is.

**Comment by Knito58** [comment]
Same Version as above v1.6.3.16 (on MC 1.12.2 Forge 14.23.2.2624 Optifine HD U D1  Singleplayer) but another issue: World stays invisible. Only the rain was shown. But the world was there and the avatar did not fall through. Going back to 1.6.2.13 fixes this for me. No crash.

**Comment by fnuecke** [comment]
Hmm, can only explain this by some mod returning `null` from `Block.getPickBlock`, not `ItemStack.EMPTY` as it should by now. Thanks for reporting!

New version up on curse, under review. Archived the old 1.11+1.12 ones.

If you still see this in MC1.12-1.6.3.17 or MC1.11.2-1.6.3.35 please reopen with new logs, thank you!

(Due to Curse possibly taking ages because it's Easter, you could also get the latest build from here http://ci.cil.li/job/Scannable-MC1.12/17/ or here http://ci.cil.li/job/Scannable-MC1.11/35/ to verify this is (hopefully) fixed.)

**Comment by Knito58** [comment]
To clarify: The scanner was not in use. Not even built. It was the only mod I updated at that time and it happened on world loading. It was easy to figure out which mod it was as the count was 1. :)
Thanks for caring and happy easter! 
I will silently wait for an official release.

**Comment by fnuecke** [comment]
Yeah, Scannable builds a block state id -> oredict name lookup table when entering the world for better performance during scans; due to a change I made to add better support for some mods, ironically that could now error due to certain mods (basically I'm trying harder to resolve block state to specific stack for mods that use meta to differentiate ores; the method used could return `null` from some mods where they should really return `ItemStack.EMPTY` by now, causing an exception).

New 1.6.3 build which should no longer error is approved on Curse now.

Thanks, and happy Easter to you, too :)

**Comment by artdude543** [comment]
@fnuecke it appears this is still an issue for a user on SevTech I've linked the issue above and this is the log being posted by their game. https://gist.github.com/Murazriel/491e9d7c4fa6573282f417d0ad0e7b50 We are in version 1.6.3 however. But appears our issue is differing to the OP.

**Comment by fnuecke** [comment]
Yeah, screwup on my part due to hastily trying to fix this before packing my bags and going on vacation (see comments on #43). Should be properly fixed now, new version is being processed on Curse right now.
