### ISSUE TITLE
[1.6.3.20]Functionality of scanning common or rare ores becomes invalid

### ISSUE THREAD

**Issue by nizhuan-jjr** [MightyPirates/Scannable#48]
Whether the ores is vanilla or custom, the scanner won't show the location for them now.

Prepared to scan
![2018-08-22_11 30 23](https://user-images.githubusercontent.com/3255986/44441595-f9bda900-a5ff-11e8-8d3b-150a7d0a826d.png)

Right after the scan
![2018-08-22_11 30 34](https://user-images.githubusercontent.com/3255986/44441615-0d690f80-a600-11e8-9436-f81ffbe75506.png)

Actual location of the ores(left:oreGold; up:oreCoal; bottom:oreRuby(from Pixelmon Reforged 6.3.4); right: pixelmon:fire_stone_ore(from Pixelmon Reforged 6.3.4))
![2018-08-22_11 31 45](https://user-images.githubusercontent.com/3255986/44441624-1f4ab280-a600-11e8-9b4c-d4c784574522.png)

This is the scannable configuration file which I added the support to Pixelmon Reforged 6.3.4.
[scannable.cfg.txt](https://github.com/MightyPirates/Scannable/files/2308792/scannable.cfg.txt)

**Comment by nizhuan-jjr** [comment]
The animal module and the monster module work fine.

**Comment by fnuecke** [comment]
Yeah, it still renders the results, they're just barely/not really visible due to OptiFine shaders and the scan effect/result rendering not being "compatible" so to say. Usually this just resulted in slightly off coloring/brightness, but it's much worse when the shaders use a gbuffer for example. I've just not had the time to work around this until now.

However! In the next build this should work with all kinds of shaders now, as I'm rendering the effect and results in the UI layer basically, which shaders shouldn't really touch anyway. This needs some extra work, so only doing that when shaders are actually in use, but yeah.
