### ISSUE TITLE
[Suggestion] Altering Modules and Scan Snapshot

### ISSUE THREAD

**Issue by Tellingohn** [MightyPirates/Scannable#54]
- Altering how Bright or Dark an individual module scans appears. (Maybe a shapeless recipe with a piece of Glowstone or Coal?) This would useful for example increasing the brightness of Rare ores and Dimming Common Ores, so that when using multiple modules in a scan one can be seen easier than another.

- An Item that records and displays a snapshot of the last scan with it in hand as well (or equiped). Doesn't display any new scan results but continues to highlight the blocks (probably will need its own visual range). I'm guessing this might be better on performance being able to hold the last scan result, rather than doing a bunch of scans like your trying to take a photo of a ghost (:P) [even tho that sounds kinda fun too]

**Comment by hron84** [comment]
TBH few presses of F2 should solve the second one but it's still a good idea. For gameplay:
 - Scanshotter must be held in offhand
 - It can only store one scan at a time. Another scan overrides previous results.
 - Technically, the scanshot should be player-bound, not item-bound. Item is just for showing it. Otherwise, players would start to collect scanshotters from different areas and it could cause storing a lot of info about blocks and locations in some data files...

**Comment by fnuecke** [comment]
Hey, thanks for the feedback and ideas. Not planning to move the mod in that direction, though, sorry. To only scan occasionally to get an idea in what direction to go is intentional.

Re brightness: in the 1.15 version block results now also show a label when looked at, should make it easy enough to tell what is what now. Currently no plans on backporting that to 1.12 though.
