### ISSUE TITLE
Conflict with The One Probe Mod

### ISSUE THREAD

**Issue by alorg** [MightyPirates/Scannable#68]
Hi, so when I look at your tool whilst I have The One Probe Mod on it Immediately crashes.
[crash-2020-08-29_22.47.47-client.txt](https://github.com/MightyPirates/Scannable/files/5177698/crash-2020-08-29_22.47.47-client.txt)

Mind having a look?

**Comment by VariableVixen** [comment]
Not a conflict, and not actually related to TOP. The error is at [lines 127-129 of ItemScanner](https://github.com/MightyPirates/Scannable/blob/9bb789f1b6da9d21bcc6d8986c1f57d8fa4162a8/src/main/java/li/cil/scannable/common/item/ItemScanner.java#L127-L129), in the `getDurabilityForDisplay()` method:

```
java.lang.NoSuchMethodError: net.minecraftforge.common.util.LazyOptional.map(Lnet/minecraftforge/common/util/NonNullFunction;)Lnet/minecraftforge/common/util/LazyOptional;
	at li.cil.scannable.common.item.ItemScanner.getDurabilityForDisplay(ItemScanner.java:128) ~[?:1.7.0.3] {re:classloading,pl:object_holder_definalize:A}
	[...snip...]
```

Anything that calls this method will crash, because the `LazyOptional<IEnergyStorage> energyStorage` doesn't have a `LazyOptional map(NonNullFunction)` method, which is called on line 128. As a temporary workaround until MightyPirates can implement a fix, you can disable energy usage, as the `getDurabilityForDisplay()` method [shortcuts out if energy usage is disabled](https://github.com/MightyPirates/Scannable/blob/9bb789f1b6da9d21bcc6d8986c1f57d8fa4162a8/src/main/java/li/cil/scannable/common/item/ItemScanner.java#L122-L124), which will avoid the `.map()` call.

**Comment by fnuecke** [comment]
Ah, so that returns `java/lang/Optional` now and they added an explicit `lazyMap`. 

Since the mappings for 1.16.3 are still riddled with holes I won't do a "proper" 1.16.3 version for now, but I've worked around this, so if there's not a bunch of other incompatibilities that'll pop up this might suffice.
