### ISSUE TITLE
[1.11.2 - 1.2.2.12] Scanning for grass blocks gives poor results

### ISSUE THREAD

**Issue by VallenFrostweaver** [MightyPirates/Scannable#8]
Setting the block scanner to scan for a grass block seem to only detect a couple nearby that are mostly surrounded by water while I am standing in a field of grass blocks. Tried different grass blocks thinking it was detecting blocks connecting to it but same results.
![grass](https://cloud.githubusercontent.com/assets/13642054/25799519/28191834-33dd-11e7-99bc-27a8f99dbec8.png)

EDIT: Further testing has inconsistent results on some more mundane stuff. Stone either lights up everything or nothing at all for example. Sand shows an area instead of just the sand blocks and it included water.
![sand](https://cloud.githubusercontent.com/assets/13642054/25799800/67431f4a-33de-11e7-8b7b-9b31613df7f0.png)

**Comment by fnuecke** [comment]
Scannable clusters adjacent results, primarily to avoid render performance going to hell when displaying many results. You'll be getting one huge cluster for the connected surface grass. And you can't see it because you're standing inside it and backfaces are getting culled (again, render performance). Haven't come up with an elegant solution to making this less confusing yet.

**Comment by fnuecke** [comment]
76317e640ee752840f6f100316aace498ca62534

Bounding boxes the camera is inside of are now put in a separate render list which is rendered with backface culling off. Should make it clearer.
