### ISSUE TITLE
[Compatibility Issue] Doesnt detect Ore Stone Variants from Ore Variants

### ISSUE THREAD

**Issue by Corvus20** [MightyPirates/Scannable#81]
When scanning, the scanner picks up other variant types of ores (terracotta, blackstone, andesite, etc.), but the (stone) variants do not. I have tried this with multiple ore types, and it seems to be a universal problem with that one variant type. This may be a problem on their end, but figured I would check here, too.
Comparison of ore variants on scanner:
![2021-01-19_12 43 25](https://user-images.githubusercontent.com/75586106/105072794-3487cd80-5a54-11eb-929d-4caaecf3d5f3.png)
The variant type (always has "(Stone)" at the end):
![Screenshot 2021-01-19 124428](https://user-images.githubusercontent.com/75586106/105072822-3ce00880-5a54-11eb-943e-f2b273298738.png)

**Comment by fnuecke** [comment]
What version of Minecraft is this?
In 1.16.x the unrecognized blocks may be missing the appropriate tag.
In 1.12... things were messier.

**Comment by Corvus20** [comment]
Sorry for the delayed reply. This is 1.16.x, yeah.  Additionally, the "sonar wave" effect doesn't seem to be rendering for me. I tried turning fast render off, and it still hadn't re-appeared.

**Comment by fnuecke** [comment]
I tried reproducing this, but I might be missing some crucial info here.
- What version of Scannable are you using? If not latest, please update and see what happens.
- What version of OSV are your using? I tested with Ore Stone Variants-5.10-1.16.4.
- What modules do you have installed? I tested with a single Block Module. It could be configured to individual variants as expected (in particular they did *not* all show up as "... (Stone)"). This worked for configuration via in-world and GUI configuration. As expected, only the configured blocks were detected. When configuring to the regular Stone variant, this also worked.
- The Common Ores module does *not* pick up variations, because they are not tagged with the `forge:ores` tag. Note that were they tagged correctly (in particular with the specific tags, too, e.g. `forge:ores/iron`) they should also be colored correctly. Tagging is up to OSV/the mod pack maker.

So all in all, cannot reproduce, behaves as expected for me.


Regarding the effect issue: the latest versions fixed rendering in Fabulous render mode.
If you're using OptiFine, this is a known incompatibility, tracked via #77.

**Comment by Corvus20** [comment]
I have been using version 5.10-1.16.4 as well. I am using Scannable version 1.16.4-1.7.3.16, the latest version. I used the common ores and range modules. I do not fully understand the "they tagged correctly" but "should also be colored correctly" explanation. So this is a problem on OSV's end? Would there be anything the dev could implement to fix it? I could relay any info to them, as I am on their discord server.

**Comment by fnuecke** [comment]
Apologies for the late reply. Yes, I'd expect OSV to tag their ores. That is datapack stuff though, so you could also add the ores to the appropriate tags yourself.
