### ISSUE TITLE
Scanner not working at all 1.16.4

### ISSUE THREAD

**Issue by deadspidervenom** [MightyPirates/Scannable#83]
Jar name: Scannable-MC1.16.4-1.7.2.15

I have 217 mods, so I am not sure what is causing it, so any suggestions on the type of mod that could be causing this can help narrow down the list.

What is happening: I Charged the device, added modules, held right click to scan, the scanning bar shows up and completes, then nothing. no errors, no effects, no ores showing and no mobs.

**Comment by fnuecke** [comment]
Please see if 1.7.3 fixes this for you, it fixed a pretty significant bug regarding how ignored blocks were handled. Thanks.

**Comment by deadspidervenom** [comment]
Still not working.

**Comment by fnuecke** [comment]
Have you checked if any errors or warnings show up in your log files when starting or ideally while/after trying to perform a scan?

**Comment by deadspidervenom** [comment]
None, i checked the entirety of my active logs, nothing related to scannable, and the errors that are there are just common things that are false negatives.

**Comment by fnuecke** [comment]
Does it work if Scannable is the only mod present? To see if it's a hardware/context problem, instead of a mod-incompatibility one.

If it works then, I'm afraid I can't think on any obvious reasons it would be incompatible with other mods. Except stuff like Optifine, i.e. things that modify MC's rendering. I'm afraid you'll have to break it down by ripping out half of them to see if it's still broken, rinse and repeat.

Is this Singleplayer, Server, Singleplayer opened to LAN?

What modules are you testing with? If configurable ones, configured with what and which way?

**Comment by deadspidervenom** [comment]
It works on its own.

Singleplayer alone.

All the modules have been tested. Configured ones i have tried both modded and vanilla stuff.

Ill check to see if any of the mods i use effect rendering.

**Comment by deadspidervenom** [comment]
![2021-01-27_10 31 09](https://user-images.githubusercontent.com/12871122/106037013-f65d6000-608a-11eb-9199-8784dbf65865.png)

So umm, noticed this while testing to see if it was working.

**Comment by deadspidervenom** [comment]
alright found the incompatibility. Seems to be this mod
https://www.curseforge.com/minecraft/mc-mods/laser-relays

When installed it does the above screenshot with the effects.(lucky for me, idc about the mod, as it had a duplication glitch and was subpar)

**Comment by fnuecke** [comment]
Hey, sorry for the late reply. I did have a look into this but never made actual progress, I'm afraid. I sadly also don't have the time to further debug this. Again, though, thanks for helping look into this.
