### ISSUE TITLE
1.18-forge-1.7.4+3.jar - Vanilla Deepslate Ores Not Registered by Rare Ore Module

### ISSUE THREAD

**Issue by Endmateria** [MightyPirates/Scannable#97]
Hey, I know I can configure this manually... but just wanted to note that by default, the rare ore module, does not register one or more of the deepslate ores. This first came to my attention when I noticed that deepslate diamond wasn't showing up in the scans.  It only seems to be seeing the deepslate gold veins.  I didn't do extensive research/troubleshooting/mod isolating on this (sorry, I'm very lethargic at the moment), just wanted to make a note of it.  I have no mods that add worldgen, so this is in reference to the vanilla deepslate ores.  P.S. I'm one of the silent majority that just "downloads it" without really paying any homage, but since I'm already here, might as well take the time to say thank you for making and maintaining this mod... it's the best ore finding mods out there in my opinion.  Good design. Thank you for your work and time.

MC Version: 1.18
Mod Version: scannable-1.18-forge-1.7.4+3.jar

Side note: I'm playing client-side only with a minimal mod load (62 mods).
And yes, Optifine is among them... but all the other ores are scanning just fine and if I make an independent module just for deepslate diamond, it scans just fine.

**Comment by fnuecke** [comment]
Yeah, sorry about that, known issue. I considered adding the tags myself, but there's a [pending Forge PR](https://github.com/MinecraftForge/MinecraftForge/pull/7891) for this (adding the new ore blocks to the general `forge:ores` tag), which hopefully gets merged soon. I'd like to wait and see what they decide, how things should be tagged. If that turns out to be incompatible with what we need for scannable, I'd probably add a new `scannable:ores` tag as a second aggregator tag. We'll see.

**Comment by fnuecke** [comment]
PR was merged.
